# Registries defined within cri-o.
crio_insecure_registries:
  - 91.208.52.222:8080

# Auth config for the registries
crio_registry_auth:
  - registry: 91.208.52.222:8080
    username: admin
    password: Meme#t0Meme#t0
