apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: podinfo
      version: '6.9.1'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: podinfo
      interval: 10m
  values:
    replicaCount: 2
