apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-nginx
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ops@sanch.pet
        privateKeySecretRef:
            name: letsencrypt-nginx
        solvers:
        - http01:
            ingress:
                class: nginx
